services:
  build-image:
    image: builder
    command: bash -c "echo build-image completed."
    build: .
  build-app:
    image: builder
    command: bash -c "make build-app"
    depends_on:
      - build-image
    volumes:
      - .:/app
    working_dir: /app
    user: appuser
