name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-buildroot:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - name: Run Build
      run: docker compose run --rm build-app
